### ISSUE TITLE
Problem z Drukuj formularz przelewu/wpłaty 

### ISSUE THREAD

**Issue by prezesk** [lmsgit/lms#1183]
Cześć,
Podczas próby wydrukowania formularza przelewu pojawia się taki błąd:
lms/vendor/rospdf/pdf-php/src/include/TTF.php[651]: Internal error - formatType is 0.0
Aktualna wersja z git.
composer update zrobione:
Package operations: 0 installs, 7 updates, 0 removals
  - Updating phpmailer/phpmailer (v5.2.23 => v5.2.24): Downloading (100%)
  - Updating rospdf/pdf-php (0.12.22 => 0.12.40): Downloading (100%)
  - Updating datatables/datatables (1.10.13 => 1.10.15): Downloading (100%)
  - Updating setasign/fpdi (1.6.1 => 1.6.2): Downloading (100%)
  - Updating tecnickcom/tcpdf (6.2.12 => 6.2.13): Downloading (100%)
  - Updating setasign/fpdi-tcpdf (1.6.1 => 1.6.2): Downloading (100%)
  - Updating pear/mail (1.3.0 => v1.4.1): Downloading (100%)
Package phine/exception is abandoned, you should avoid using it. No replacement was suggested.
Package phine/observer is abandoned, you should avoid using it. No replacement was suggested.
Writing lock file
Generating autoload files
> sed -i -e 's/class HTML2PDF_myPdf extends TCPDF/class HTML2PDF_myPdf extends LMSTCPDF/' vendor/spipu/html2pdf/_class/myPdf.class.php
> sed -i -e 's/\(\s\+\)register_shutdown_function/\1\/\/register_shutdown_function/' vendor/tecnickcom/tcpdf/tcpdf.php
> cp -f lib/ezpdf/fonts/arial* vendor/rospdf/pdf-php/src/fonts
system:
Debian GNU/Linux 8

**Comment by interduo** [comment]
A co masz w opcjach phpui ?

**Comment by prezesk** [comment]
phpui | accountlist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy kont. Domyślnie: 100. |  
-- | -- | -- | -- | --
phpui | add_customer_group_required | false | Ustawienie opcji na "true" wymusza wybór grupy przypisanej do klienta. Domyślnie wyłączone |  
phpui | aliaslist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy aliasów. Domyślnie: 100. |  
phpui | allow_from |   | Lista sieci i adresów IP z dostępem do LMS-a. Jeżeli jest pusta każdy może uzyskać dostęp do systemu. Jeżeli wpiszesz tutaj listę adresów i puli adresowych, to LMS będzie odrzucał każdego niepowołanego użytkownika zwracając błąd HTTP 403 |  
phpui | allow_mac_sharing | false | Zezwolenie na dodawanie komputerów ze zduplikowanymi adresami MAC (LMS nie sprawdza czy inny komputer nie ma już przypisanego danego adresu MAC). Domyślnie: 0 (wyłączone). |  
phpui | autosuggest_max_length | 40 | Maksymalna długość wyświetlanych podpowiedzi, w przypadku przekroczenia dalszy napis zostanie zakropkowany. |  
phpui | balancelist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie bilansu klienta. Domyślnie: 100. |  
phpui | big_networks | false | Wsparcie dla dużych providerów, np. ukrywanie długich list wyboru klientów. Domyślnie: wyłączona. |  
phpui | billinglist_pagelimit | 100 | Limit wyświetlanych bilingów na jednej stronie. Domyślnie: 100. |  
phpui | cashreglog_pagelimit | 100 | Nieznana opcja. Brak opisu. |  
phpui | check_for_updates_period | 86400 | Jak często sprawdzać czy są dostępne uaktualnienia LMS-a (w sekundach). Domyślnie: 86400. |  
phpui | configlist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy opcji konfiguracyjnych. Domyślnie: 100. |  
phpui | customerlist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy klientów. Domyślnie: 100. |  
phpui | debitnotelist_pagelimit | 100 | Nieznana opcja. Brak opisu. |  
phpui | default_address |   | Domyślny kod pocztowy, miasto, ulica pod czas dodawania nowego klienta. Przydatne kiedy mamy wielu klientów na tej samej ulicy. |  
phpui | default_assignment_invoice | 0 | Nieznana opcja. Brak opisu. |  
phpui | default_assignment_period | 3 | Domyślna wartość okresu obciążenia. Domyślnie: 0 |  
phpui | default_autosuggest_placement | bottom | Domyślne umiejscowienie okna sugestii (left/right/top/bottom) |  
phpui | default_city |   | Domyślny kod pocztowy, miasto, ulica pod czas dodawania nowego klienta. Przydatne kiedy mamy wielu klientów na tej samej ulicy. |  
phpui | default_editor | html | Nieznana opcja. Brak opisu. |  
phpui | default_module | welcome | Nazwa modułu startowego (nazwa pliku z katalogu /modules bez rozszerzenia). Domyślnie: welcome |  
phpui | default_monthly_payday |   | Domyślny dzień miesiąca przypisywany nowym płatnościom miesięcznym. Domyślnie: 0 (niezdefiniowany). |  
phpui | default_taxrate | 23 | Wartość stawki procentowej, która ma być domyślnie zaznaczona na listach wyboru stawki. Domyślnie: 22.0 |  
phpui | default_teryt_city | false | Domyślne Miasto dla TERYT. Wprowadź id Miasta z TERYT. |  
phpui | default_zip |   | Domyślny kod pocztowy, miasto, ulica pod czas dodawania nowego klienta. Przydatne kiedy mamy wielu klientów na tej samej ulicy. |  
phpui | divisionlist_pagelimit | 100 | Limit ilości rekordów na liście firm. Domyślnie: 100. |  
phpui | document_margins | 10,5,15,5 | Nieznana opcja. Brak opisu. |  
phpui | documentlist_pagelimit | 100 | Limit rekordów na jednej stronie listy dokumentów. Domyślnie: 100. |  
phpui | domainlist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy domen. Domyślnie: 100. |  
phpui | event_usergroup_selection_type | update | Nieznana opcja. Brak opisu. |  
phpui | ewx_support | false | Włącza wsparcie dla urządzeń EtherWerX. Domyślnie: wyłączona |  
phpui | force_ssl | true | Wymuszanie SSL. Ustawienie tej opcji na 1 sprawi, że LMS wymusi przekierowanie do połączenia SSL poprzez wykonanie przekierowania do 'https://'.$_SERVER[HTTP_HOST].$_SERVER[REQUEST_URI] Przy każdej próbie dostępu z wyjątkiem SSL. Domyślnie: 0 (off). |  
phpui | gd_translate_to | ISO-8859-2 | Strona kodowa danych dla biblioteki gd (przydatne gdy np. gd wymaga ISO-8859-2 zamiast UTF-8 w funkcji imagetext(). |  
phpui | helpdesk_backend_mode | false | Kiedy włączona, wszystkie wiadomości w systemie Helpdesk (oprócz tych od zgłaszającego) będą wysyłane do serwera pocztowego na adres odpowiedniej kolejki. Skrypt lms-rtparser powinien być uruchomiony na serwerze. Wiadomości do bazy danych zostaną zapisane przez skrypt. Domyślnie: wyłączone. |  
phpui | helpdesk_customerinfo | true | Dodaje podstawowe informacje o kliencie w widoku zgłoszenia oraz w powiadomieniach. Domyślnie: włączona |  
phpui | helpdesk_customerinfo_mail_body | -- Klient: %custname ID: %cid Adres: %address E-mail: %email Telefon: %phone | Szablon dla powiadomień email użytkowników, odnoszący się do danych klienta w zgłoszeniach w Helpdesk. %custname - nazwa klienta ; %cid - id klienta ; %address - adres klienta ; %email - adresy e-mail ; %phone - telefony |  
phpui | helpdesk_customerinfo_sms_body | Klient: %custname ID: %cid Adres: %address Telefon: %phone | Szablon dla powiadomień email użytkowników, odnoszący się do danych klienta w zgłoszeniach w Helpdesk. %custname - nazwa klienta ; %cid - id klienta ; %address - adres klienta ; %email - adresy e-mail ; %phone - telefony |  
phpui | helpdesk_notification_mail_body | %body URL: %url %customerinfo | Szablon tekstu dla powiadomień użytkowników o zgłoszeniach w Helpdesk. %status - status zgłoszenia ; %cat - kategorie zgłoszenia ; %tid - id zgłoszenia ; %cid - id klienta ; %subject - temat zgłoszenia ; %body - treść zgłoszenia ; %url - url zgłoszenia ; %customerinfo - informacje o kliencie |  
phpui | helpdesk_notification_mail_subject | [RT#%tid] %subject | Szablon tekstu dla powiadomień użytkowników o zgłoszeniach w Helpdesk. %status - status zgłoszenia ; %cat - kategorie zgłoszenia ; %tid - id zgłoszenia ; %cid - id klienta ; %subject - temat zgłoszenia ; %body - treść zgłoszenia ; %url - url zgłoszenia ; %customerinfo - informacje o kliencie |  
phpui | helpdesk_notification_sms_body | [RT#%tid] %subject: %body %customerinfo | Szablon tekstu dla powiadomień użytkowników o zgłoszeniach w Helpdesk. %status - status zgłoszenia ; %cat - kategorie zgłoszenia ; %tid - id zgłoszenia ; %cid - id klienta ; %subject - temat zgłoszenia ; %body - treść zgłoszenia ; %url - url zgłoszenia ; %customerinfo - informacje o kliencie |  
phpui | helpdesk_reply_body | false | Dodaje ciało wiadomości w odpowiedzi. Domyślnie: nie. |  
phpui | helpdesk_sender_name |   | Nazwa nadawcy wiadomości lub jedna z predefiniowanych wartości: "queue" - nazwa kolejki, "user" - zalogowany użytkownik. Domyślnie: pusta. |  
phpui | helpdesk_stats | true | Dodaje statystyki przyczyn zgłoszeń na stronie podglądu zgłoszenia oraz jego wydruku. Domyślnie: włączona |  
phpui | hide_toolbar | false | Ukryj górne menu w interfejsie użytkownika. Domyślnie: 0 (wyłączone). |  
phpui | homedir_prefix | /home/ | Prefiks katalogu domowego dla konta. Domyślnie: /home/ |  
phpui | invoice_check_payment | false | Nieznana opcja. Brak opisu. |  
phpui | invoicelist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy faktur. Domyślnie: 100. |  
phpui | lang | pl | Kod językowy systemu. Jeżeli nie jest wybrany to język będzie bazował na ustawieniach przeglądarki. Domyślnie: en. Komentarz: pl |  
phpui | lastonline_limit | 600 | Określ czas (w sekundach) po jakim komputer będzie uważany za wyłączony. Powinno się to pokrywać z częstotliwością uruchamiania skryptu dokonującego sprawdzenia aktywności komputerów (np lms-fping). Domyślnie: 600. |  
phpui | logging | false | Czy ta instalacja LMS posiada log transakcji (opcja nie opensource). Domyślnie: 0 (wyłączone). |  
phpui | messagelist_pagelimit | 100 | Nieznana opcja. Brak opisu. |  
phpui | networkhosts_pagelimit | 256 | Limit wyświetlanych komputerów na jednej stronie w Informacjach o Sieci. Domyślnie: 256. Ustawiając na 0, informacje te zostaną pominięte (strona będzie się wyświetlać szybciej). |  
phpui | newticket_notify | false | Gdy włączona, system wyśle informacje o dodaniu nowego zgłoszenia do wszystkich użytkowników, którzy mają prawa do konkretnej kolejki. Domyślnie: wyłączona. |  
phpui | nodelist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy komputerów. Domyślnie: 100. |  
phpui | note_check_payment | false | Nieznana opcja. Brak opisu. |  
phpui | numberplanlist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy planów numeracyjnych. Domyślnie: 100. |  
phpui | passwordhistory | 6 | Nieznana opcja. Brak opisu. |  
phpui | ping_type | 1 | Domyślny rodzaj pinga. Możesz użyć "1" dla pinga lub "2" dla arpinga. Domyślnie: 1. |  
phpui | plugins |   | Nieznana opcja. Brak opisu. |  
phpui | public_ip | 1 | Nieznana opcja. Brak opisu. |  
phpui | quicksearch_limit | 15 | Nieznana opcja. Brak opisu. |  
phpui | radius | 1 | Nieznana opcja. Brak opisu. |  
phpui | receiptlist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy dowodów wpłaty. Domyślnie: 100. |  
phpui | recordlist_pagelimit | 100 | Nieznana opcja. Brak opisu. |  
phpui | reload_execcmd | /bin/true | Komenda która ma zostać wykonana podczas przeładowania jeżeli reload_type jest ustawiony na 'exec'. Domyślnie /bin/true. Ciąg znaków jest przesyłany do funkcji system(), więc sugeruję żebyś uważał co robisz i jak :) Pomimo tego że średniki powinny być odpowiednio interpretowane przez powłokę bash LMS rozdziela takie komendy i uruchamia je pojedynczo. |  
phpui | reload_sqlquery |   | Zapytanie SQL wykonywane pod czas przeładownia jeżeli reload_type = sql. Domyślnie: pusta. W zapytaniu może być użyta zmienna '%TIME%' jako zastępstwo właściwego czasu zapisanego w formacie UNIX_TIMESTAMP. UWAGA! Średnik jest interpretowany jako znak rozdzielający zapytania. Oznacza to, że możesz wpisać kilka zapytań SQL oddzielonych średnikami. |  
phpui | reload_type | sql | Typ przeładowania. Dostępne opcje: exec - wykonanie komendy (najczęściej jakiego skryptu lub innego programu przy użyciu sudo - konfigurowalne dalej); sql - zapisuje zlecenie w bazie danych SQL (konkretne zapytanie sql również może być zdefiniowane). |  
phpui | settings_timeout | 28800 | Nieznana opcja. Brak opisu. |  
phpui | short_pagescroller | false | Włącza formularz zmiany strony zaprojektowany z myślą o listach z bardzo dużą ilością stron. Domyślnie: wyłączona |  
phpui | smarty_debug | false | Włącza konsolę debugowania Smarty. Przydatne do śledzenia wartości przekazywanych w PHP do szablonów. Domyślnie: 0 (wyłączona). |  
phpui | taxratelist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy stawek podatkowych. Domyślnie: 100. |  
phpui | ticket_template_file | rtticketprint.html | Szablon wydruku zgłoszenia. Domyślnie: rtticketprint.html |  
phpui | ticketlist_pagelimit | 100 | Limit wyświetlanych rekordów na jednej stronie listy zgłoszeń. Domyślnie: 100. |  
phpui | ticketlist_status |   | Domyślne ustawienie filtra statusu na liście zgłoszeń. Dozwolonych wartości szukaj w kodzie html strony. Domyślnie: nie ustawiona |  
phpui | timeout | 600 | Czas wygaśnięcia sesji. Po tym czasie (określonym w sekundach) użytkownik zostanie wylogowany jeżeli nie podejmie żadnej akcji. Domyślnie: 600. |  
phpui | timetable_days_forward | 7 | Ilość dni w kalendarzu (włączając dzień dzisiejszy). Domyślnie: 7. |  
phpui | to_words_short_version | false | Określ typ reprezentacji słownej liczb (na fakturach). np dla wartości "1" słowne określenie sumy 123,15 wędzie wyglądało "jed dwa trz 15/100". Domyślnie: 0. |  
phpui | use_current_payday | false | Wybieraj aktualny dzień miesiąca jako dzień tworzenia nowych płatności. Domyślnie: 0 (Wyłączone). |  
phpui | use_invoices | false | Sprawia że opcja "z fakturą" będzie domyślnie zaznaczona. Domyślnie: 0 |  
phpui | voipaccountlist_pagelimit | 100 | Nieznana opcja. Brak opisu. |

**Comment by prezesk** [comment]
Czy brakuje jakiegoś wpisu?

**Comment by prezesk** [comment]
Ustaliłem że jak dodałem opcje pdf_type = ezpdf w invoice uzyskałem taki sam błąd przy generowaniu faktury jak przy generowaniu formularza przelewu. Błąd ten to: 
lms/vendor/rospdf/pdf-php/src/include/TTF.php[651]: Internal error - formatType is 0.0
po zmianie pdf_type=tcpdf faktury generują się poprawnie. 
Ale nie wiem gdzie jest to ustalane dla formularzy przelewów. 
Proszę o pomoc.

**Comment by interduo** [comment]
Poradziłeś sobie z tym?

**Comment by prezesk** [comment]
Nadal nie potrafię tego rozwiązać. Jestem w tym samym miejscu.

**Comment by interduo** [comment]
Jak drukujesz ten formularz?

**Comment by prezesk** [comment]
Przez finanse-> raporty -> Formularze przelewu.

**Comment by interduo** [comment]
Ja mam u siebie to:
Warning: Division by zero in /var/www/html/lmpt/vendor/rospdf/pdf-php/src/Cpdf.php on line 1950
Warning: Division by zero in /var/www/html/lmpt/vendor/rospdf/pdf-php/src/Cpdf.php on line 1951
Warning: Division by zero in /var/www/html/lmpt/vendor/rospdf/pdf-php/src/Cpdf.php on line 1952
Warning: Division by zero in /var/www/html/lmpt/vendor/rospdf/pdf-php/src/Cpdf.php on line 1953

/var/www/html/lmpt/vendor/rospdf/pdf-php/src/include/TTF.php[651]: Internal error - formatType is 0.

Mogę potwierdzić więc problem. Nie potrafiłem odwzorować problemu ponieważ ja generuję druczki inaczej.

**Comment by prezesk** [comment]
To może podpowiedz jak to robić inaczej i może mi także zadziała i nie będę musiał się męczyć :)

**Comment by interduo** [comment]
Ty to dobrze robisz to powinno być naprawione. Tymczasowo możesz drukować druczki z poziomu userpanelu do czasu naprawienia błedu.

**Comment by chilek** [comment]
Nie potwierdzam problemu - zarówno na demo.lms.org.pl jak i stable.lms.org.pl działa bez błędów.

**Comment by interduo** [comment]
a na demo.lms.org.pl masz tło druczka?

**Comment by chilek** [comment]
Na demo i stable jest:
```sh
# composer info
Do not run Composer as root/super user! See https://getcomposer.org/root for details
components/jquery        3.2.1   jQuery JavaScript Library
components/jqueryui      1.12.1  jQuery UI is a curated set of user interface interactions, effects, widgets, and themes built on top of the jQuery JavaScript Library. Whether you're bu...
components/normalize.css 3.0.3   Normalize.css is a customisable CSS file that makes browsers render all elements more consistently and in line with modern standards.
datatables/datatables    1.10.16 DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon the foundations of progressive enhancement, which wi...
pear/console_getopt      v1.4.1  More info available on: http://pear.php.net/package/Console_Getopt
pear/mail                v1.4.1  Class that provides multiple interfaces for sending emails.
pear/pear-core-minimal   v1.10.3 Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception      v1.0.0  The PEAR Exception base class.
phine/exception          1.0.0   A PHP library for improving the use of exceptions.
phine/observer           2.0.0   A PHP library that implements the observer pattern.
phpmailer/phpmailer      v5.2.25 PHPMailer is a full-featured email creation and transfer class for PHP
rospdf/pdf-php           0.12.41 The R&OS Pdf class supports the creation of PDF documents without any adiditional modules or extensions.
setasign/fpdi            1.6.2   FPDI is a collection of PHP classes facilitating developers to read pages from existing PDF documents and use them as templates in FPDF. Because it is a...
setasign/fpdi-tcpdf      1.6.2   Kind of metadata package for dependencies of the latest versions of FPDI and TCPDF.
smarty/smarty            v3.1.31 Smarty - the compiling PHP template engine
spipu/html2pdf           v4.6.1  HTML2PDF is a HTML to PDF converter written in PHP5 (it uses TCPDF). OFFICIAL PACKAGE
tecnickcom/tcpdf         6.2.13  TCPDF is a PHP class for generating PDF documents and barcodes.
xdan/datetimepicker      2.5.4  
```
> a na demo.lms.org.pl masz tło druczka?

Przecież standardowo nie ma tam żadnych druczków przelewu.

**Comment by interduo** [comment]
A na produkcji jak w tą opcję kliknę mam:

Fatal error: Uncaught Error: Call to undefined function bcadd() in /var/www/html/lms/vendor/rospdf/pdf-php/src/include/TTF.php:1168 Stack trace: #0 /var/www/html/lms/vendor/rospdf/pdf-php/src/include/TTF.php(54): TTF::getUlong('\x00\x01\x00\x00\x00\x17\x01\x00\x00\x04\x00pDSI...', 16) #1 /var/www/html/lms/vendor/rospdf/pdf-php/src/Cpdf.php(1908): TTF->__construct('\x00\x01\x00\x00\x00\x17\x01\x00\x00\x04\x00pDSI...') #2 /var/www/html/lms/vendor/rospdf/pdf-php/src/Cpdf.php(2143): Cpdf->openFont('arial') #3 /var/www/html/lms/lib/LMSDocuments/LMSEzpdfBackend.php(85): Cpdf->selectFont('arial', Array, 1, true) #4 /var/www/html/lms/lib/LMSDocuments/LMSDocument.php(33): LMSEzpdfBackend->__construct('A4', 'landscape', 'Formularz przel...') #5 /var/www/html/lms/lib/LMSDocuments/LMSEzpdfTransferForm.php(31): LMSDocument->__construct('LMSEzpdfBackend', 'Formularz przel...', 'A4', 'landscape') #6 /var/www/html/lms/modules/transferforms.php(68): LMSEzpdfTransferForm->__construct('Formularz przel...', 'A4', 'landscape') #7 /var/www/htm in /var/www/html/lms/vendor/rospdf/pdf-php/src/include/TTF.php on line 1168

**Comment by interduo** [comment]
Na testowym LMS:

Jeśli nie wybiorę żadnego klienta i kliknę wydrukuj mam tylko:
`/var/www/html/lmpt/vendor/rospdf/pdf-php/src/include/TTF.php[651]: Internal error - formatType is 0.0.`

```
components/jquery        3.2.1   jQuery JavaScript Library
components/jqueryui      1.12.1  jQuery UI is a curated set of user interface interactions, effects, widgets, and themes built on top o...
components/normalize.css 3.0.3   Normalize.css is a customisable CSS file that makes browsers render all elements more consistently and...
datatables/datatables    1.10.16 DataTables is a plug-in for the jQuery Javascript library. It is a highly flexible tool, based upon th...
pear/console_getopt      v1.4.1  More info available on: http://pear.php.net/package/Console_Getopt
pear/mail                v1.4.1  Class that provides multiple interfaces for sending emails.
pear/pear-core-minimal   v1.10.3 Minimal set of PEAR core files to be used as composer dependency
pear/pear_exception      v1.0.0  The PEAR Exception base class.
phine/exception          1.0.0   A PHP library for improving the use of exceptions.
phine/observer           2.0.0   A PHP library that implements the observer pattern.
phpmailer/phpmailer      v5.2.25 PHPMailer is a full-featured email creation and transfer class for PHP
rospdf/pdf-php           0.12.41 The R&OS Pdf class supports the creation of PDF documents without any adiditional modules or extensions.
setasign/fpdi            1.6.2   FPDI is a collection of PHP classes facilitating developers to read pages from existing PDF documents ...
setasign/fpdi-tcpdf      1.6.2   Kind of metadata package for dependencies of the latest versions of FPDI and TCPDF.
smarty/smarty            v3.1.31 Smarty - the compiling PHP template engine
spipu/html2pdf           v4.6.1  HTML2PDF is a HTML to PDF converter written in PHP5 (it uses TCPDF). OFFICIAL PACKAGE
tecnickcom/tcpdf         6.2.13  TCPDF is a PHP class for generating PDF documents and barcodes.
xdan/datetimepicker      2.5.4 
```

**Comment by interduo** [comment]
![formularz_przelewu](https://user-images.githubusercontent.com/17087236/31344297-92f46e70-ad12-11e7-8a58-ed509802fec4.png)

To ma docelowo tak wyglądać?

**Comment by chilek** [comment]
Zgłoszenie nie dotyczyło tego jak ma to wyglądać, tylko tego, że komuś nie działa.

**Comment by interduo** [comment]
@chilek jeśli ustawię jako backend ezPDF również i faktury przestają mi się drukować i mam ten sam błąd. Wniosek, że modules/transferforms.php zawsze korzysta z ezPDF. U mnie ezPDF się sypie.

Czy jest jakaś zmienna, która sprawi by używał tecnickcom/tcpdf ?

**Comment by prezesk** [comment]
No to proszę o jakieś info jak zainstalować ezPDF. Na debianie najlepiej. lub tak jak kolega interduo zasugerował jakieś rozwiązanie aby działało na tcpdf.

**Comment by interduo** [comment]
Wystarczy, że sobie zmienne w phpui zmienisz i działa to.
