### ISSUE TITLE
Nie działa podstrona "Interfejs użytkownika"

### ISSUE THREAD

**Issue by kyob** [lmsgit/lms#934]
Branch master.

Próba otwarcia **?m=configlist** kończy się zapętleniem widać tylko spinner.

**Comment by chilek** [comment]
Zapętlenie jest tylko wrażeniem. Sprawdź w konsoli javascript jaki błąd się generuje, a przede wszystkim zrób twardy reload witryny LMS w przeglądarce. Może być potrzebne włączenie w inspektorze DOM pominięcia cache przeglądarki.

**Comment by kyob** [comment]
Błędy w consoli:
```js
XHR finished loading: GET "http://192.168.12.2/img/jquery-datatables-i18n/pl.json".
jQuery.Deferred exception: Cannot read property 'trim' of undefined TypeError: Cannot read property 'trim' of undefined
    at HTMLTableRowElement.<anonymous> (http://192.168.12.2/img/jquery.js:317:43)
    at Function.each (http://192.168.12.2/img/jquery/jquery.min.js:2:2815)
    at r.each (http://192.168.12.2/img/jquery/jquery.min.js:2:1003)
    at HTMLTableCellElement.<anonymous> (http://192.168.12.2/img/jquery.js:316:52)
    at Function.each (http://192.168.12.2/img/jquery/jquery.min.js:2:2815)
    at r.each (http://192.168.12.2/img/jquery/jquery.min.js:2:1003)
    at initDataTable (http://192.168.12.2/img/jquery.js:309:45)
    at HTMLTableElement.<anonymous> (http://192.168.12.2/img/jquery.js:493:3)
    at Function.each (http://192.168.12.2/img/jquery/jquery.min.js:2:2815)
    at r.each (http://192.168.12.2/img/jquery/jquery.min.js:2:1003) undefined
Uncaught TypeError: Cannot read property 'trim' of undefined
```

**Comment by chilek** [comment]
Jaka to przeglądarka www i w jakiej wersji?

**Comment by kyob** [comment]
Chromium - Version 53.0.2785.116 Fedora Project (64-bit)

**Comment by kyob** [comment]
Firefox 49.0 wynik w załączniku.
[firebug.pdf](https://github.com/lmsgit/lms/files/504583/firebug.pdf)

**Comment by chilek** [comment]
Proszę o zrzut błędu z konsoli javascript dla bieżącej wersji master - chodzi mi o to, żebyśmy patrzyli na te same wiersze skryptu img/jquery.js.

**Comment by kyob** [comment]
![spinner](https://cloud.githubusercontent.com/assets/689112/19034688/34e9b2c6-8965-11e6-8989-09349a62a259.png)

**Comment by chilek** [comment]
Czyli wywala Ci się na wierszu:
https://github.com/lmsgit/lms/blob/master/img/jquery.js#L317
?

**Comment by chilek** [comment]
Na 100% masz uaktualnione jquery i jqueryui? Spróbuj na wszelki wypadek uruchomić:
**composer update** w katalogu głównym LMS-a.

**Comment by kyob** [comment]
OK problem był u mnie :)

Miałem włączony **xdebug** w php.
```php
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
```

Także na przyszłość polecam każdemu:
composer clear-cache
composer self-update
composer diagnose

Zamykam :)
